### ISSUE TITLE
Separate prediction and update steps

### ISSUE THREAD

**Issue by dressel** [JuliaPOMDP/ParticleFilters.jl#18]
Often times filtering is split into prediction and update steps. For particle filters, the prediction step consists of propagating the particle states forward according to the system dynamics. The update step consists of incorporating the measurement by weighting according to observation likelihood and resampling.

It may be more efficient to perform these steps together, but I at least think there should be an `update(filter, b, a)` function that simply propagates the states forward for the user. It's not hard for the user to do but it would be convenient to have such a function. Thoughts?

**Comment by zsunberg** [comment]
Hmm maybe... initial thoughts are:

1. This is simple enough to do without us giving a function, i.e. the one liner
```
collect(generate_s(model, s, a, rng) for s in particles(b)))
```
would do.
2. It should be called `predict` instead of `update`.

**Comment by zsunberg** [comment]
Additional initial thought:

3. Having `update` call `predict!` `reweight!`, and `resample` steps actually seems like a really good idea. We should do that.

**Comment by dressel** [comment]
I don't care if it is `predict` instead of `update`. And yes, it is easy to do without a function, but I think it's a matter of convenience for the user.

My only concern with splitting it within the `update` function itself is that it requires a second pass through the particle collection. Right now, after generating the next state for a particle, you immediately weight it by the observation likelihood. If there is a performance penalty, it will probably be negligible? I don't know.

**Comment by ebalaban** [comment]
Personally, I like `update` rather than `predict` for the high-level function. I think `'update` is a far more established term for it.  I also share @dressel's concern that there may be some performance penalty for splitting up `predict` and `reweight` steps (there is usually a collective `normalize` substep after `reweight`, but it could be moved into `resample`).

**Comment by zsunberg** [comment]
FYI I'm working on this right now

**Comment by MaximeBouton** [comment]
I am voting for `predict` instead of `update`, I think `update` is wrapping the whole "filtering" or "state estimation" process which often involves two steps: prediction, comparison of measurement and prediction. 
`update` is established for the belief update part but is more than just prediction.
