### ISSUE TITLE
Best way to implement a mixed state particle filter

### ISSUE THREAD

**Issue by hmzh-khn** [JuliaPOMDP/ParticleFilters.jl#57]
Hello,
What's the best way to implement a mixed state particle filter with this library? I'm interested in exploring a contribution rather than a from-scratch implementation. I looked through the code briefly, but haven't found an obvious way to do it.

By mixed state, I mean that there is a set of discrete states of finite support that each particle can be in and dynamics/measurement likelihoods associated with each state.

Thanks

**Comment by WhiffleFish** [comment]
Hi,

You say mixed state but describe a finite discrete state process.

Could you mean a process where the state contains both continuous and discrete components?

**Comment by hmzh-khn** [comment]
Yes that is what I mean. The state would contain both discrete and continuous components.

**Comment by WhiffleFish** [comment]
Right, this can be treated the same as a continuous state space.

For example, we can define a POMDP with a state containing a discrete component (`Bool`) and a continuous component (`Float64`).

If we want to use something like the `BootstrapFilter`, then we only need to define a generative dynamics function and an explicit observation/measurement distribution.

```julia
using POMDPs, ParticleFilters, Distributions
const MIXED_S = Tuple{Bool, Float64}

struct MixedPOMDP <: POMDP{MIXED_S, Bool, MIXED_S} end

POMDPs.initialstate(::MixedPOMDP) = Dirac((false, 0.0))

POMDPs.observation(::MixedPOMDP, sp::MIXED_S) = product_distribution(
    [Bernoulli(sp[1] ? 0.9 : 0.1), Normal(sp[2], 1.0)]
)

function POMDPs.gen(m::MixedPOMDP, s, a, rng)
    sp = (
        (rand(rng) < 0.75) ? s[1] : !s[1],
        s[2] + a + randn(rng)
    )
    o = rand(rng, observation(m, sp))
    r = 0.0
    return (;sp, o, r)
end
```

We can test that it works with the following script:

```julia
pomdp = MixedPOMDP()
n_particles = 100
T = 50
pf = BootstrapFilter(pomdp, n_particles)
b = initialize_belief(pf, initialstate(pomdp))
s = rand(initialstate(pomdp))
a = true
b_hist = [b.particles]
s_hist = [s]

for i ∈ 1:T-1
    s, o, r = @gen(:sp,:o,:r)(pomdp, s, a)
    b = update(pf, b, a, o)
    push!(s_hist, s)
    push!(b_hist, b.particles)
end

using Plots

X = reduce(vcat, fill(i, n_particles) for i ∈ eachindex(b_hist, s_hist))
Y_1 = reduce(vcat, map(b->getindex.(b,1), b_hist))
Y_2 = reduce(vcat, map(b->getindex.(b,2), b_hist))

p1 = scatter(X, Y_1, label="particle state", markeralpha=0.1, title="x₁ (discrete)")
plot!(p1,1:T, getindex.(s_hist, 1), label="true state", c=:red, lw=3)

p2 = scatter(X, Y_2, label="particle state", markeralpha=0.1, title="x₂ (continuous)")
plot!(p2, 1:T, getindex.(s_hist, 2), label="true state", c=:red, lw=3)
p = plot(p1, p2)
```

![final_plot](https://user-images.githubusercontent.com/52610169/210639634-daec6fe8-3216-476a-a1f7-9fb13b632100.png)

**Comment by hmzh-khn** [comment]
This approach isn't quite as flexible as I need, but I appreciate that the lack of flexibility is not a result of ParticleFilters.jl. Closing the issue.
